# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
encoding:         utf-8
title:            Christopher Ko
tagline:
description:      "Mathematics and Engineering Student at Queen's University in Kingston"
url:
baseurl:          /

author:
  name:          Christopher Ko
  url:

paginate:         5

# Custom vars
version:          0.5

github:
  repo:           https://github.com/chriskopher

linkedin:
  link:           https://ca.linkedin.com/in/kochristopher

email:
  link:           mailto:christopher.ko@queensu.ca
