# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
encoding:         utf-8
title:            Christopher Ko
tagline:
description:      "Mathematics and Engineering Student at Queen's University in Kingston, Ontario"
url:
baseurl:          /

author:
  name:          Christopher Ko
  url:

paginate:         5

# Custom vars
version:          1.0.0

github: 
  repo:           https://github.com/chriskopher

linkedin:
  link:           https://ca.linkedin.com/in/kochristopher

email:
  link:           mailto:christopher.ko@queensu.ca

github: [metadata]

plugins:
  - jekyll-sitemap
